Streamline install/execute
* Add gyp build step to install instructions

Running `npx parser` fails if the cityhash native code wasn't compiled, and the error message Node gives may be misleading:

node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^
Error: ENOENT: no such file or directory, open '-i'

So mentioning the native compilation step in the readme seems important.

This change adds a script command for the compilation, as suggested by @truckermudgeon.

* Increase Node heap size for parser

With all current map DLC installed, running `npx parser` requires about 5 GB of memory on my machine (x64 Mac), but the default heap size limit seems to be just 4 GB. As a result, parsing may fail with the message:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

This change adds an argument that increases the memory limit to 8 GB to the parser script.